In [ ]:
import numpy as np  
# Load the ECG data
data = np.loadtxt('data/ECGu.txt')

# Display it
print (data)
print("Number of points:", len(data))

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
Number of points: 6500
