In [3]:
# Load the ECG data
data = np.loadtxt('data/ECGu.txt')

# Display it
print (data)
print("Number of points:", len(data))

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
Number of points: 6500


# Arrival point : 
Detect heartbeats and compute heart rate from the raw ECG signal.

# Starting point : 
Raw voltage values loaded from 'ECGu.txt'

# Steps : 
1. Load the data
2. Plot the raw ECG data
3. Convert to mV / seconds
4. Plot rescaled data 
5. Rename vars, refactor, docstrings


In [4]:
import numpy as np  
import matplotlib.pyplot as plt

In [5]:
raw_ECG = np.loadtxt('data/ECGu.txt')